#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_girl002_Preview_Phy

#include "Basic.hpp"

#include "ABP_girl002_Preview_Phy_classes.hpp"
#include "ABP_girl002_Preview_Phy_parameters.hpp"


namespace SDK
{

// Function ABP_girl002_Preview_Phy.ABP_girl002_Preview_Phy_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_girl002_Preview_Phy_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_girl002_Preview_Phy_C", "AnimGraph");

	Params::ABP_girl002_Preview_Phy_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_girl002_Preview_Phy.ABP_girl002_Preview_Phy_C.ExecuteUbergraph_ABP_girl002_Preview_Phy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_girl002_Preview_Phy_C::ExecuteUbergraph_ABP_girl002_Preview_Phy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_girl002_Preview_Phy_C", "ExecuteUbergraph_ABP_girl002_Preview_Phy");

	Params::ABP_girl002_Preview_Phy_C_ExecuteUbergraph_ABP_girl002_Preview_Phy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

