#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CupIceCream

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CupIceCream.BP_CupIceCream_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_CupIceCream_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CupIceCream_C_ReceiveTick;

// Function BP_CupIceCream.BP_CupIceCream_C.ExecuteUbergraph_BP_CupIceCream
// 0x0008 (0x0008 - 0x0000)
struct BP_CupIceCream_C_ExecuteUbergraph_BP_CupIceCream final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_CupIceCream_C_ExecuteUbergraph_BP_CupIceCream;

// Function BP_CupIceCream.BP_CupIceCream_C.SetStrawberryLiquid
// 0x0001 (0x0001 - 0x0000)
struct BP_CupIceCream_C_SetStrawberryLiquid final
{
public:
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_CupIceCream_C_SetStrawberryLiquid;

}

