#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DropShoeComponent

#include "Basic.hpp"

#include "BP_DropShoeComponent_classes.hpp"
#include "BP_DropShoeComponent_parameters.hpp"


namespace SDK
{

// Function BP_DropShoeComponent.BP_DropShoeComponent_C.On Enter Scene
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SceneType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DropShoeComponent_C::On_Enter_Scene(int32 SceneType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DropShoeComponent_C", "On Enter Scene");

	Params::BP_DropShoeComponent_C_On_Enter_Scene Parms{};

	Parms.SceneType = SceneType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DropShoeComponent.BP_DropShoeComponent_C.OnEnterNormalScene
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_DropShoeComponent_C::OnEnterNormalScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DropShoeComponent_C", "OnEnterNormalScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DropShoeComponent.BP_DropShoeComponent_C.OnEnterFeatureScene
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_DropShoeComponent_C::OnEnterFeatureScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DropShoeComponent_C", "OnEnterFeatureScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DropShoeComponent.BP_DropShoeComponent_C.DropShoe
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Shoe                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DropShoeComponent_C::DropShoe(int32 Shoe)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DropShoeComponent_C", "DropShoe");

	Params::BP_DropShoeComponent_C_DropShoe Parms{};

	Parms.Shoe = Shoe;

	UObject::ProcessEvent(Func, &Parms);
}

}

