#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Girl002_Preview

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Girl_Preview_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Girl002_Preview.BP_Girl002_Preview_C
// 0x0008 (0x07A0 - 0x0798)
class ABP_Girl002_Preview_C final : public ABP_Girl_Preview_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Girl002_Preview_C;               // 0x0798(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_BP_Girl002_Preview(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Girl002_Preview_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Girl002_Preview_C")
	}
	static class ABP_Girl002_Preview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Girl002_Preview_C>();
	}
};
DUMPER7_ASSERTS_ABP_Girl002_Preview_C;

}

