#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HouseFurnitureBase

#include "Basic.hpp"

#include "BP_HouseFurnitureBase_classes.hpp"
#include "BP_HouseFurnitureBase_parameters.hpp"


namespace SDK
{

// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ShowOrHideTagMesh
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             InTag                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Hide                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_HouseFurnitureBase_C::ShowOrHideTagMesh(class FName InTag, bool Hide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ShowOrHideTagMesh");

	Params::BP_HouseFurnitureBase_C_ShowOrHideTagMesh Parms{};

	Parms.InTag = InTag;
	Parms.Hide = Hide;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.SubSkmStopMontageAndHide
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USkeletalMeshComponent*           TargetSkm                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::SubSkmStopMontageAndHide(class USkeletalMeshComponent* TargetSkm)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "SubSkmStopMontageAndHide");

	Params::BP_HouseFurnitureBase_C_SubSkmStopMontageAndHide Parms{};

	Parms.TargetSkm = TargetSkm;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.SubSkmPlayMontage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USkeletalMeshComponent*           TargetSkm                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimMontage*                     TargetMontage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::SubSkmPlayMontage(class USkeletalMeshComponent* TargetSkm, class UAnimMontage* TargetMontage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "SubSkmPlayMontage");

	Params::BP_HouseFurnitureBase_C_SubSkmPlayMontage Parms{};

	Parms.TargetSkm = TargetSkm;
	Parms.TargetMontage = TargetMontage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.OnGraphicsQualityChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPlanarReflectionComponent*       PlanarReflection                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::OnGraphicsQualityChanged(class UPlanarReflectionComponent* PlanarReflection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "OnGraphicsQualityChanged");

	Params::BP_HouseFurnitureBase_C_OnGraphicsQualityChanged Parms{};

	Parms.PlanarReflection = PlanarReflection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.OptimizePlanarReflection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPlanarReflectionComponent*       PlanarReflection                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::OptimizePlanarReflection(class UPlanarReflectionComponent* PlanarReflection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "OptimizePlanarReflection");

	Params::BP_HouseFurnitureBase_C_OptimizePlanarReflection Parms{};

	Parms.PlanarReflection = PlanarReflection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ShowCG__Overridden
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Path                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    BGMStateGroup                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::ShowCG__Overridden(const class FString& Path, const class FString& BGMStateGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ShowCG__Overridden");

	Params::BP_HouseFurnitureBase_C_ShowCG__Overridden Parms{};

	Parms.Path = std::move(Path);
	Parms.BGMStateGroup = std::move(BGMStateGroup);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.SpawnEffectAutoDestroyed
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraSystem*                   InEffect                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFXSystemComponent*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UFXSystemComponent* ABP_HouseFurnitureBase_C::SpawnEffectAutoDestroyed(class UNiagaraSystem* InEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "SpawnEffectAutoDestroyed");

	Params::BP_HouseFurnitureBase_C_SpawnEffectAutoDestroyed Parms{};

	Parms.InEffect = InEffect;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.SpawnEffect
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraSystem*                   InEffect                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFXSystemComponent*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UFXSystemComponent* ABP_HouseFurnitureBase_C::SpawnEffect(class UNiagaraSystem* InEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "SpawnEffect");

	Params::BP_HouseFurnitureBase_C_SpawnEffect Parms{};

	Parms.InEffect = InEffect;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_HouseFurnitureBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_HouseFurnitureBase_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_HouseFurnitureBase_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ReceiveActorBeginOverlap");

	Params::BP_HouseFurnitureBase_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.SetEffectParamInTimeLine
// (Event, Public, BlueprintEvent)
// Parameters:
// class UFXSystemComponent*               InEffect                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Speed                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsReverse                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FName                             ValueName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::SetEffectParamInTimeLine(class UFXSystemComponent* InEffect, float Speed, bool IsReverse, class FName ValueName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "SetEffectParamInTimeLine");

	Params::BP_HouseFurnitureBase_C_SetEffectParamInTimeLine Parms{};

	Parms.InEffect = InEffect;
	Parms.Speed = Speed;
	Parms.IsReverse = IsReverse;
	Parms.ValueName = ValueName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.OnQualityChanged_Event_0
// (BlueprintCallable, BlueprintEvent)

void ABP_HouseFurnitureBase_C::OnQualityChanged_Event_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "OnQualityChanged_Event_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_HouseFurnitureBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ExecuteUbergraph_BP_HouseFurnitureBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::ExecuteUbergraph_BP_HouseFurnitureBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ExecuteUbergraph_BP_HouseFurnitureBase");

	Params::BP_HouseFurnitureBase_C_ExecuteUbergraph_BP_HouseFurnitureBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// LuaFunction BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.ShowCG
// (Native, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Path                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    BGMStateGroup                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_HouseFurnitureBase_C::ShowCG(const class FString& Path, const class FString& BGMStateGroup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "ShowCG");

	Params::BP_HouseFurnitureBase_C_ShowCG Parms{};

	Parms.Path = std::move(Path);
	Parms.BGMStateGroup = std::move(BGMStateGroup);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_HouseFurnitureBase.BP_HouseFurnitureBase_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_HouseFurnitureBase_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HouseFurnitureBase_C", "GetModuleName");

	Params::BP_HouseFurnitureBase_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

