#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Entry_01b

#include "Basic.hpp"

#include "Entry_01b_classes.hpp"
#include "Entry_01b_parameters.hpp"


namespace SDK
{

// Function Entry_01b.Entry_01b_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEntry_01b_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Entry_01b_C", "ReceiveTick");

	Params::Entry_01b_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Entry_01b.Entry_01b_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEntry_01b_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Entry_01b_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Entry_01b.Entry_01b_C.ExecuteUbergraph_Entry_01b
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEntry_01b_C::ExecuteUbergraph_Entry_01b(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Entry_01b_C", "ExecuteUbergraph_Entry_01b");

	Params::Entry_01b_C_ExecuteUbergraph_Entry_01b Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

