#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FieldSystemEngine

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Chaos_structs.hpp"


namespace SDK
{

// Class FieldSystemEngine.FieldSystemActor
// 0x0008 (0x0230 - 0x0228)
class AFieldSystemActor final : public AActor
{
public:
	class UFieldSystemComponent*                  FieldSystemComponent;                              // 0x0228(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystemActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystemActor")
	}
	static class AFieldSystemActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFieldSystemActor>();
	}
};
DUMPER7_ASSERTS_AFieldSystemActor;

// Class FieldSystemEngine.FieldSystem
// 0x0010 (0x0038 - 0x0028)
class UFieldSystem final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystem")
	}
	static class UFieldSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldSystem>();
	}
};
DUMPER7_ASSERTS_UFieldSystem;

// Class FieldSystemEngine.FieldSystemComponent
// 0x0030 (0x0490 - 0x0460)
class UFieldSystemComponent final : public UPrimitiveComponent
{
public:
	class UFieldSystem*                           FieldSystem;                                       // 0x0458(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_460[0x10];                                     // 0x0460(0x0010)(Fixing Size After Last Property [ Rei-SdkDumper ])
	TArray<TSoftObjectPtr<class AChaosSolverActor>> SupportedSolvers;                                // 0x0470(0x0010)(Edit, ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8                                         Pad_480[0x10];                                     // 0x0480(0x0010)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	void AddFieldCommand(bool Enabled, EFieldPhysicsType Target, class UFieldSystemMetaData* MetaData, class UFieldNodeBase* Field);
	void ApplyLinearForce(bool Enabled, const struct FVector& Direction, float Magnitude);
	void ApplyPhysicsField(bool Enabled, EFieldPhysicsType Target, class UFieldSystemMetaData* MetaData, class UFieldNodeBase* Field);
	void ApplyRadialForce(bool Enabled, const struct FVector& Position, float Magnitude);
	void ApplyRadialVectorFalloffForce(bool Enabled, const struct FVector& Position, float Radius, float Magnitude);
	void ApplyStayDynamicField(bool Enabled, const struct FVector& Position, float Radius);
	void ApplyStrainField(bool Enabled, const struct FVector& Position, float Radius, float Magnitude, int32 Iterations);
	void ApplyUniformVectorFalloffForce(bool Enabled, const struct FVector& Position, const struct FVector& Direction, float Radius, float Magnitude);
	void ResetFieldSystem();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystemComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystemComponent")
	}
	static class UFieldSystemComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldSystemComponent>();
	}
};
DUMPER7_ASSERTS_UFieldSystemComponent;

// Class FieldSystemEngine.FieldSystemMetaData
// 0x0000 (0x00B0 - 0x00B0)
class UFieldSystemMetaData : public UActorComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystemMetaData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystemMetaData")
	}
	static class UFieldSystemMetaData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldSystemMetaData>();
	}
};
DUMPER7_ASSERTS_UFieldSystemMetaData;

// Class FieldSystemEngine.FieldSystemMetaDataIteration
// 0x0008 (0x00B8 - 0x00B0)
class UFieldSystemMetaDataIteration final : public UFieldSystemMetaData
{
public:
	int32                                         Iterations;                                        // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UFieldSystemMetaDataIteration* SetMetaDataIteration(int32 Iterations_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystemMetaDataIteration")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystemMetaDataIteration")
	}
	static class UFieldSystemMetaDataIteration* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldSystemMetaDataIteration>();
	}
};
DUMPER7_ASSERTS_UFieldSystemMetaDataIteration;

// Class FieldSystemEngine.FieldSystemMetaDataProcessingResolution
// 0x0008 (0x00B8 - 0x00B0)
class UFieldSystemMetaDataProcessingResolution final : public UFieldSystemMetaData
{
public:
	EFieldResolutionType                          ResolutionType;                                    // 0x00B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UFieldSystemMetaDataProcessingResolution* SetMetaDataaProcessingResolutionType(EFieldResolutionType ResolutionType_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldSystemMetaDataProcessingResolution")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldSystemMetaDataProcessingResolution")
	}
	static class UFieldSystemMetaDataProcessingResolution* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldSystemMetaDataProcessingResolution>();
	}
};
DUMPER7_ASSERTS_UFieldSystemMetaDataProcessingResolution;

// Class FieldSystemEngine.FieldNodeBase
// 0x0000 (0x00B0 - 0x00B0)
class UFieldNodeBase : public UActorComponent
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldNodeBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldNodeBase")
	}
	static class UFieldNodeBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldNodeBase>();
	}
};
DUMPER7_ASSERTS_UFieldNodeBase;

// Class FieldSystemEngine.FieldNodeInt
// 0x0000 (0x00B0 - 0x00B0)
class UFieldNodeInt : public UFieldNodeBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldNodeInt")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldNodeInt")
	}
	static class UFieldNodeInt* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldNodeInt>();
	}
};
DUMPER7_ASSERTS_UFieldNodeInt;

// Class FieldSystemEngine.FieldNodeFloat
// 0x0000 (0x00B0 - 0x00B0)
class UFieldNodeFloat : public UFieldNodeBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldNodeFloat")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldNodeFloat")
	}
	static class UFieldNodeFloat* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldNodeFloat>();
	}
};
DUMPER7_ASSERTS_UFieldNodeFloat;

// Class FieldSystemEngine.FieldNodeVector
// 0x0000 (0x00B0 - 0x00B0)
class UFieldNodeVector : public UFieldNodeBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FieldNodeVector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FieldNodeVector")
	}
	static class UFieldNodeVector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldNodeVector>();
	}
};
DUMPER7_ASSERTS_UFieldNodeVector;

// Class FieldSystemEngine.UniformInteger
// 0x0008 (0x00B8 - 0x00B0)
class UUniformInteger final : public UFieldNodeInt
{
public:
	int32                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UUniformInteger* SetUniformInteger(int32 Magnitude_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UniformInteger")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UniformInteger")
	}
	static class UUniformInteger* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUniformInteger>();
	}
};
DUMPER7_ASSERTS_UUniformInteger;

// Class FieldSystemEngine.RadialIntMask
// 0x0020 (0x00D0 - 0x00B0)
class URadialIntMask final : public UFieldNodeInt
{
public:
	float                                         Radius;                                            // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Position;                                          // 0x00B4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         InteriorValue;                                     // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ExteriorValue;                                     // 0x00C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESetMaskConditionType                         SetMaskCondition;                                  // 0x00C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class URadialIntMask* SetRadialIntMask(float Radius_0, const struct FVector& Position_0, int32 InteriorValue_0, int32 ExteriorValue_0, ESetMaskConditionType SetMaskConditionIn);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RadialIntMask")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RadialIntMask")
	}
	static class URadialIntMask* GetDefaultObj()
	{
		return GetDefaultObjImpl<URadialIntMask>();
	}
};
DUMPER7_ASSERTS_URadialIntMask;

// Class FieldSystemEngine.UniformScalar
// 0x0008 (0x00B8 - 0x00B0)
class UUniformScalar final : public UFieldNodeFloat
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UUniformScalar* SetUniformScalar(float Magnitude_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UniformScalar")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UniformScalar")
	}
	static class UUniformScalar* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUniformScalar>();
	}
};
DUMPER7_ASSERTS_UUniformScalar;

// Class FieldSystemEngine.RadialFalloff
// 0x0028 (0x00D8 - 0x00B0)
class URadialFalloff final : public UFieldNodeFloat
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinRange;                                          // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxRange;                                          // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Default;                                           // 0x00BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Radius;                                            // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Position;                                          // 0x00C4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFieldFalloffType                             Falloff;                                           // 0x00D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class URadialFalloff* SetRadialFalloff(float Magnitude_0, float MinRange_0, float MaxRange_0, float Default_0, float Radius_0, const struct FVector& Position_0, EFieldFalloffType Falloff_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RadialFalloff")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RadialFalloff")
	}
	static class URadialFalloff* GetDefaultObj()
	{
		return GetDefaultObjImpl<URadialFalloff>();
	}
};
DUMPER7_ASSERTS_URadialFalloff;

// Class FieldSystemEngine.PlaneFalloff
// 0x0030 (0x00E0 - 0x00B0)
class UPlaneFalloff final : public UFieldNodeFloat
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinRange;                                          // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxRange;                                          // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Default;                                           // 0x00BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Distance;                                          // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Position;                                          // 0x00C4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Normal;                                            // 0x00D0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFieldFalloffType                             Falloff;                                           // 0x00DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_DD[0x3];                                       // 0x00DD(0x0003)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UPlaneFalloff* SetPlaneFalloff(float Magnitude_0, float MinRange_0, float MaxRange_0, float Default_0, float Distance_0, const struct FVector& Position_0, const struct FVector& Normal_0, EFieldFalloffType Falloff_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PlaneFalloff")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlaneFalloff")
	}
	static class UPlaneFalloff* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlaneFalloff>();
	}
};
DUMPER7_ASSERTS_UPlaneFalloff;

// Class FieldSystemEngine.BoxFalloff
// 0x0050 (0x0100 - 0x00B0)
class UBoxFalloff final : public UFieldNodeFloat
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinRange;                                          // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxRange;                                          // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Default;                                           // 0x00BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTransform                             Transform;                                         // 0x00C0(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	EFieldFalloffType                             Falloff;                                           // 0x00F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F1[0xF];                                       // 0x00F1(0x000F)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UBoxFalloff* SetBoxFalloff(float Magnitude_0, float MinRange_0, float MaxRange_0, float Default_0, const struct FTransform& Transform_0, EFieldFalloffType Falloff_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BoxFalloff")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BoxFalloff")
	}
	static class UBoxFalloff* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBoxFalloff>();
	}
};
DUMPER7_ASSERTS_UBoxFalloff;

// Class FieldSystemEngine.NoiseField
// 0x0040 (0x00F0 - 0x00B0)
class UNoiseField final : public UFieldNodeFloat
{
public:
	float                                         MinRange;                                          // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxRange;                                          // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B8[0x8];                                       // 0x00B8(0x0008)(Fixing Size After Last Property [ Rei-SdkDumper ])
	struct FTransform                             Transform;                                         // 0x00C0(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

public:
	class UNoiseField* SetNoiseField(float MinRange_0, float MaxRange_0, const struct FTransform& Transform_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NoiseField")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NoiseField")
	}
	static class UNoiseField* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNoiseField>();
	}
};
DUMPER7_ASSERTS_UNoiseField;

// Class FieldSystemEngine.UniformVector
// 0x0010 (0x00C0 - 0x00B0)
class UUniformVector final : public UFieldNodeVector
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Direction;                                         // 0x00B4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	class UUniformVector* SetUniformVector(float Magnitude_0, const struct FVector& Direction_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("UniformVector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UniformVector")
	}
	static class UUniformVector* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUniformVector>();
	}
};
DUMPER7_ASSERTS_UUniformVector;

// Class FieldSystemEngine.RadialVector
// 0x0010 (0x00C0 - 0x00B0)
class URadialVector final : public UFieldNodeVector
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Position;                                          // 0x00B4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	class URadialVector* SetRadialVector(float Magnitude_0, const struct FVector& Position_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RadialVector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RadialVector")
	}
	static class URadialVector* GetDefaultObj()
	{
		return GetDefaultObjImpl<URadialVector>();
	}
};
DUMPER7_ASSERTS_URadialVector;

// Class FieldSystemEngine.RandomVector
// 0x0008 (0x00B8 - 0x00B0)
class URandomVector final : public UFieldNodeVector
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class URandomVector* SetRandomVector(float Magnitude_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RandomVector")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomVector")
	}
	static class URandomVector* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomVector>();
	}
};
DUMPER7_ASSERTS_URandomVector;

// Class FieldSystemEngine.OperatorField
// 0x0020 (0x00D0 - 0x00B0)
class UOperatorField final : public UFieldNodeBase
{
public:
	float                                         Magnitude;                                         // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Rei-SdkDumper ])
	class UFieldNodeBase*                         RightField;                                        // 0x00B8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFieldNodeBase*                         LeftField;                                         // 0x00C0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFieldOperationType                           Operation;                                         // 0x00C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UOperatorField* SetOperatorField(float Magnitude_0, const class UFieldNodeBase* RightField_0, const class UFieldNodeBase* LeftField_0, EFieldOperationType Operation_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OperatorField")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OperatorField")
	}
	static class UOperatorField* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOperatorField>();
	}
};
DUMPER7_ASSERTS_UOperatorField;

// Class FieldSystemEngine.ToIntegerField
// 0x0008 (0x00B8 - 0x00B0)
class UToIntegerField final : public UFieldNodeInt
{
public:
	class UFieldNodeFloat*                        FloatField;                                        // 0x00B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	class UToIntegerField* SetToIntegerField(const class UFieldNodeFloat* FloatField_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ToIntegerField")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ToIntegerField")
	}
	static class UToIntegerField* GetDefaultObj()
	{
		return GetDefaultObjImpl<UToIntegerField>();
	}
};
DUMPER7_ASSERTS_UToIntegerField;

// Class FieldSystemEngine.ToFloatField
// 0x0008 (0x00B8 - 0x00B0)
class UToFloatField final : public UFieldNodeFloat
{
public:
	class UFieldNodeInt*                          IntField;                                          // 0x00B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	class UToFloatField* SetToFloatField(const class UFieldNodeInt* IntegerField);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ToFloatField")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ToFloatField")
	}
	static class UToFloatField* GetDefaultObj()
	{
		return GetDefaultObjImpl<UToFloatField>();
	}
};
DUMPER7_ASSERTS_UToFloatField;

// Class FieldSystemEngine.CullingField
// 0x0018 (0x00C8 - 0x00B0)
class UCullingField final : public UFieldNodeBase
{
public:
	class UFieldNodeBase*                         Culling;                                           // 0x00B0(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFieldNodeBase*                         Field;                                             // 0x00B8(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EFieldCullingOperationType                    Operation;                                         // 0x00C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	class UCullingField* SetCullingField(const class UFieldNodeBase* Culling_0, const class UFieldNodeBase* Field_0, EFieldCullingOperationType Operation_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CullingField")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CullingField")
	}
	static class UCullingField* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCullingField>();
	}
};
DUMPER7_ASSERTS_UCullingField;

// Class FieldSystemEngine.ReturnResultsTerminal
// 0x0000 (0x00B0 - 0x00B0)
class UReturnResultsTerminal final : public UFieldNodeBase
{
public:
	class UReturnResultsTerminal* SetReturnResultsTerminal();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ReturnResultsTerminal")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ReturnResultsTerminal")
	}
	static class UReturnResultsTerminal* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReturnResultsTerminal>();
	}
};
DUMPER7_ASSERTS_UReturnResultsTerminal;

}

