#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HouseNpc18_Suit80_AnimBp

#include "Basic.hpp"

#include "HouseNpcAnimBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass HouseNpc18_Suit80_AnimBp.HouseNpc18_Suit80_AnimBp_C
// 0x0000 (0x56C0 - 0x56C0)
class UHouseNpc18_Suit80_AnimBp_C final : public UHouseNpcAnimBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HouseNpc18_Suit80_AnimBp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HouseNpc18_Suit80_AnimBp_C")
	}
	static class UHouseNpc18_Suit80_AnimBp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHouseNpc18_Suit80_AnimBp_C>();
	}
};
DUMPER7_ASSERTS_UHouseNpc18_Suit80_AnimBp_C;

}

