#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnlineSubsystemUtils

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AudioMixer_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "OnlineSubsystem_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "DeveloperSettings_classes.hpp"


namespace SDK
{

// Class OnlineSubsystemUtils.EndMatchCallbackProxy
// 0x0050 (0x0080 - 0x0030)
class UEndMatchCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UEndMatchCallbackProxy* EndMatch(class UObject* WorldContextObject, class APlayerController* PlayerController, TScriptInterface<class ITurnBasedMatchInterface> MatchActor, const class FString& MatchID, EMPMatchOutcome LocalPlayerOutcome, EMPMatchOutcome OtherPlayersOutcome);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EndMatchCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EndMatchCallbackProxy")
	}
	static class UEndMatchCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEndMatchCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UEndMatchCallbackProxy;

// Class OnlineSubsystemUtils.AchievementBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UAchievementBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void GetCachedAchievementDescription(class UObject* WorldContextObject, class APlayerController* PlayerController, class FName AchievementID, bool* bFoundID, class FText* Title, class FText* LockedDescription, class FText* UnlockedDescription, bool* bHidden);
	static void GetCachedAchievementProgress(class UObject* WorldContextObject, class APlayerController* PlayerController, class FName AchievementID, bool* bFoundID, float* Progress);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AchievementBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AchievementBlueprintLibrary")
	}
	static class UAchievementBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAchievementBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UAchievementBlueprintLibrary;

// Class OnlineSubsystemUtils.IpNetDriver
// 0x0070 (0x07C0 - 0x0750)
class UIpNetDriver : public UNetDriver
{
public:
	uint8                                         LogPortUnreach : 1;                                // 0x0750(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         AllowPlayerPortUnreach : 1;                        // 0x0750(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Config, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_751[0x3];                                      // 0x0751(0x0003)(Fixing Size After Last Property [ Rei-SdkDumper ])
	uint32                                        MaxPortCountToTry;                                 // 0x0754(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_758[0xC];                                      // 0x0758(0x000C)(Fixing Size After Last Property [ Rei-SdkDumper ])
	uint32                                        ServerDesiredSocketReceiveBufferBytes;             // 0x0764(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint32                                        ServerDesiredSocketSendBufferBytes;                // 0x0768(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint32                                        ClientDesiredSocketReceiveBufferBytes;             // 0x076C(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint32                                        ClientDesiredSocketSendBufferBytes;                // 0x0770(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_774[0x4];                                      // 0x0774(0x0004)(Fixing Size After Last Property [ Rei-SdkDumper ])
	double                                        MaxSecondsInReceive;                               // 0x0778(0x0008)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         NbPacketsBetweenReceiveTimeTest;                   // 0x0780(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         ResolutionConnectionTimeout;                       // 0x0784(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_788[0x38];                                     // 0x0788(0x0038)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("IpNetDriver")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IpNetDriver")
	}
	static class UIpNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIpNetDriver>();
	}
};
DUMPER7_ASSERTS_UIpNetDriver;

// Class OnlineSubsystemUtils.AchievementQueryCallbackProxy
// 0x0038 (0x0068 - 0x0030)
class UAchievementQueryCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x18];                                      // 0x0050(0x0018)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UAchievementQueryCallbackProxy* CacheAchievementDescriptions(class UObject* WorldContextObject, class APlayerController* PlayerController);
	static class UAchievementQueryCallbackProxy* CacheAchievements(class UObject* WorldContextObject, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AchievementQueryCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AchievementQueryCallbackProxy")
	}
	static class UAchievementQueryCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAchievementQueryCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UAchievementQueryCallbackProxy;

// Class OnlineSubsystemUtils.AchievementWriteCallbackProxy
// 0x0050 (0x0080 - 0x0030)
class UAchievementWriteCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> OnSuccess; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class FName WrittenAchievementName, float WrittenProgress, int32 WrittenUserTag)> OnFailure; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x30];                                      // 0x0050(0x0030)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UAchievementWriteCallbackProxy* WriteAchievementProgress(class UObject* WorldContextObject, class APlayerController* PlayerController, class FName AchievementName, float Progress, int32 UserTag);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AchievementWriteCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AchievementWriteCallbackProxy")
	}
	static class UAchievementWriteCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAchievementWriteCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UAchievementWriteCallbackProxy;

// Class OnlineSubsystemUtils.ConnectionCallbackProxy
// 0x0048 (0x0078 - 0x0030)
class UConnectionCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(int32 ErrorCode)> OnSuccess;                                       // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 ErrorCode)> OnFailure;                                       // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x28];                                      // 0x0050(0x0028)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UConnectionCallbackProxy* ConnectToService(class UObject* WorldContextObject, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ConnectionCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ConnectionCallbackProxy")
	}
	static class UConnectionCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConnectionCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UConnectionCallbackProxy;

// Class OnlineSubsystemUtils.CreateSessionCallbackProxy
// 0x0068 (0x0098 - 0x0030)
class UCreateSessionCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x48];                                      // 0x0050(0x0048)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UCreateSessionCallbackProxy* CreateSession(class UObject* WorldContextObject, class APlayerController* PlayerController, int32 PublicConnections, bool bUseLAN);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CreateSessionCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CreateSessionCallbackProxy")
	}
	static class UCreateSessionCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreateSessionCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UCreateSessionCallbackProxy;

// Class OnlineSubsystemUtils.DestroySessionCallbackProxy
// 0x0048 (0x0078 - 0x0030)
class UDestroySessionCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x28];                                      // 0x0050(0x0028)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UDestroySessionCallbackProxy* DestroySession(class UObject* WorldContextObject, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DestroySessionCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DestroySessionCallbackProxy")
	}
	static class UDestroySessionCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDestroySessionCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UDestroySessionCallbackProxy;

// Class OnlineSubsystemUtils.EndTurnCallbackProxy
// 0x0048 (0x0078 - 0x0030)
class UEndTurnCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x28];                                      // 0x0050(0x0028)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UEndTurnCallbackProxy* EndTurn(class UObject* WorldContextObject, class APlayerController* PlayerController, const class FString& MatchID, TScriptInterface<class ITurnBasedMatchInterface> TurnBasedMatchInterface);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("EndTurnCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EndTurnCallbackProxy")
	}
	static class UEndTurnCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEndTurnCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UEndTurnCallbackProxy;

// Class OnlineSubsystemUtils.FindSessionsCallbackProxy
// 0x0060 (0x0090 - 0x0030)
class UFindSessionsCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> OnSuccess; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> OnFailure; // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x40];                                      // 0x0050(0x0040)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UFindSessionsCallbackProxy* FindSessions(class UObject* WorldContextObject, class APlayerController* PlayerController, int32 MaxResults, bool bUseLAN);
	static int32 GetCurrentPlayers(const struct FBlueprintSessionResult& Result);
	static int32 GetMaxPlayers(const struct FBlueprintSessionResult& Result);
	static int32 GetPingInMs(const struct FBlueprintSessionResult& Result);
	static class FString GetServerName(const struct FBlueprintSessionResult& Result);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FindSessionsCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FindSessionsCallbackProxy")
	}
	static class UFindSessionsCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFindSessionsCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UFindSessionsCallbackProxy;

// Class OnlineSubsystemUtils.FindTurnBasedMatchCallbackProxy
// 0x0058 (0x0088 - 0x0030)
class UFindTurnBasedMatchCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void(const class FString& MatchID)> OnSuccess;                          // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& MatchID)> OnFailure;                          // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x38];                                      // 0x0050(0x0038)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UFindTurnBasedMatchCallbackProxy* FindTurnBasedMatch(class UObject* WorldContextObject, class APlayerController* PlayerController, TScriptInterface<class ITurnBasedMatchInterface> MatchActor, int32 MinPlayers, int32 MaxPlayers, int32 PlayerGroup, bool ShowExistingMatches);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FindTurnBasedMatchCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FindTurnBasedMatchCallbackProxy")
	}
	static class UFindTurnBasedMatchCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFindTurnBasedMatchCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UFindTurnBasedMatchCallbackProxy;

// Class OnlineSubsystemUtils.InAppPurchaseCallbackProxy
// 0x0058 (0x0080 - 0x0028)
class UInAppPurchaseCallbackProxy final : public UObject
{
public:
	TMulticastInlineDelegate<void(EInAppPurchaseState PurchaseStatus, const struct FInAppPurchaseProductInfo& InAppPurchaseReceipts)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EInAppPurchaseState PurchaseStatus, const struct FInAppPurchaseProductInfo& InAppPurchaseReceipts)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x38];                                      // 0x0048(0x0038)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseCallbackProxy* CreateProxyObjectForInAppPurchase(class APlayerController* PlayerController, const struct FInAppPurchaseProductRequest& ProductRequest);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseCallbackProxy")
	}
	static class UInAppPurchaseCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseCallbackProxy;

// Class OnlineSubsystemUtils.InAppPurchaseCallbackProxy2
// 0x0080 (0x00A8 - 0x0028)
class UInAppPurchaseCallbackProxy2 final : public UObject
{
public:
	TMulticastInlineDelegate<void(EInAppPurchaseStatus PurchaseStatus, const TArray<struct FInAppPurchaseReceiptInfo2>& InAppPurchaseReceipts)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EInAppPurchaseStatus PurchaseStatus, const TArray<struct FInAppPurchaseReceiptInfo2>& InAppPurchaseReceipts)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x60];                                      // 0x0048(0x0060)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseCallbackProxy2* CreateProxyObjectForInAppPurchase(class APlayerController* PlayerController, const struct FInAppPurchaseProductRequest2& ProductRequest);
	static class UInAppPurchaseCallbackProxy2* CreateProxyObjectForInAppPurchaseQueryOwned(class APlayerController* PlayerController);
	static class UInAppPurchaseCallbackProxy2* CreateProxyObjectForInAppPurchaseUnprocessedPurchases(class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseCallbackProxy2")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseCallbackProxy2")
	}
	static class UInAppPurchaseCallbackProxy2* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseCallbackProxy2>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseCallbackProxy2;

// Class OnlineSubsystemUtils.InAppPurchaseQueryCallbackProxy
// 0x0068 (0x0090 - 0x0028)
class UInAppPurchaseQueryCallbackProxy final : public UObject
{
public:
	TMulticastInlineDelegate<void(const TArray<struct FInAppPurchaseProductInfo>& InAppPurchaseInformation)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const TArray<struct FInAppPurchaseProductInfo>& InAppPurchaseInformation)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x48];                                      // 0x0048(0x0048)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseQueryCallbackProxy* CreateProxyObjectForInAppPurchaseQuery(class APlayerController* PlayerController, const TArray<class FString>& ProductIdentifiers);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseQueryCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseQueryCallbackProxy")
	}
	static class UInAppPurchaseQueryCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseQueryCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseQueryCallbackProxy;

// Class OnlineSubsystemUtils.InAppPurchaseQueryCallbackProxy2
// 0x0040 (0x0068 - 0x0028)
class UInAppPurchaseQueryCallbackProxy2 final : public UObject
{
public:
	TMulticastInlineDelegate<void(const TArray<struct FOnlineProxyStoreOffer>& InAppOfferInformation)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const TArray<struct FOnlineProxyStoreOffer>& InAppOfferInformation)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x20];                                      // 0x0048(0x0020)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseQueryCallbackProxy2* CreateProxyObjectForInAppPurchaseQuery(class APlayerController* PlayerController, const TArray<class FString>& ProductIdentifiers);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseQueryCallbackProxy2")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseQueryCallbackProxy2")
	}
	static class UInAppPurchaseQueryCallbackProxy2* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseQueryCallbackProxy2>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseQueryCallbackProxy2;

// Class OnlineSubsystemUtils.InAppPurchaseRestoreCallbackProxy
// 0x0068 (0x0090 - 0x0028)
class UInAppPurchaseRestoreCallbackProxy final : public UObject
{
public:
	TMulticastInlineDelegate<void(EInAppPurchaseState CompletionStatus, const TArray<struct FInAppPurchaseRestoreInfo>& InAppRestorePurchaseInformation)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EInAppPurchaseState CompletionStatus, const TArray<struct FInAppPurchaseRestoreInfo>& InAppRestorePurchaseInformation)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x48];                                      // 0x0048(0x0048)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseRestoreCallbackProxy* CreateProxyObjectForInAppPurchaseRestore(const TArray<struct FInAppPurchaseProductRequest>& ConsumableProductFlags, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseRestoreCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseRestoreCallbackProxy")
	}
	static class UInAppPurchaseRestoreCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseRestoreCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseRestoreCallbackProxy;

// Class OnlineSubsystemUtils.InAppPurchaseRestoreCallbackProxy2
// 0x0080 (0x00A8 - 0x0028)
class UInAppPurchaseRestoreCallbackProxy2 final : public UObject
{
public:
	TMulticastInlineDelegate<void(EInAppPurchaseStatus PurchaseStatus, const TArray<struct FInAppPurchaseRestoreInfo2>& InAppPurchaseRestoreInfo)> OnSuccess; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(EInAppPurchaseStatus PurchaseStatus, const TArray<struct FInAppPurchaseRestoreInfo2>& InAppPurchaseRestoreInfo)> OnFailure; // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x60];                                      // 0x0048(0x0060)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UInAppPurchaseRestoreCallbackProxy2* CreateProxyObjectForInAppPurchaseRestore(const TArray<struct FInAppPurchaseProductRequest2>& ConsumableProductFlags, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("InAppPurchaseRestoreCallbackProxy2")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InAppPurchaseRestoreCallbackProxy2")
	}
	static class UInAppPurchaseRestoreCallbackProxy2* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInAppPurchaseRestoreCallbackProxy2>();
	}
};
DUMPER7_ASSERTS_UInAppPurchaseRestoreCallbackProxy2;

// Class OnlineSubsystemUtils.IpConnection
// 0x00A0 (0x1B90 - 0x1AF0)
class UIpConnection final : public UNetConnection
{
public:
	uint8                                         Pad_1AF0[0x50];                                    // 0x1AF0(0x0050)(Fixing Size After Last Property [ Rei-SdkDumper ])
	float                                         SocketErrorDisconnectDelay;                        // 0x1B40(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_1B44[0x4C];                                    // 0x1B44(0x004C)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("IpConnection")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IpConnection")
	}
	static class UIpConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIpConnection>();
	}
};
DUMPER7_ASSERTS_UIpConnection;

// Class OnlineSubsystemUtils.JoinSessionCallbackProxy
// 0x0150 (0x0180 - 0x0030)
class UJoinSessionCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x130];                                     // 0x0050(0x0130)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UJoinSessionCallbackProxy* JoinSession(class UObject* WorldContextObject, class APlayerController* PlayerController, const struct FBlueprintSessionResult& SearchResult);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("JoinSessionCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JoinSessionCallbackProxy")
	}
	static class UJoinSessionCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJoinSessionCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UJoinSessionCallbackProxy;

// Class OnlineSubsystemUtils.LeaderboardBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class ULeaderboardBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool WriteLeaderboardInteger(class APlayerController* PlayerController, class FName StatName, int32 StatValue);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LeaderboardBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LeaderboardBlueprintLibrary")
	}
	static class ULeaderboardBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULeaderboardBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_ULeaderboardBlueprintLibrary;

// Class OnlineSubsystemUtils.LeaderboardFlushCallbackProxy
// 0x0040 (0x0068 - 0x0028)
class ULeaderboardFlushCallbackProxy final : public UObject
{
public:
	TMulticastInlineDelegate<void(class FName SessionName)> OnSuccess;                               // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class FName SessionName)> OnFailure;                               // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x20];                                      // 0x0048(0x0020)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class ULeaderboardFlushCallbackProxy* CreateProxyObjectForFlush(class APlayerController* PlayerController, class FName SessionName);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LeaderboardFlushCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LeaderboardFlushCallbackProxy")
	}
	static class ULeaderboardFlushCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULeaderboardFlushCallbackProxy>();
	}
};
DUMPER7_ASSERTS_ULeaderboardFlushCallbackProxy;

// Class OnlineSubsystemUtils.LeaderboardQueryCallbackProxy
// 0x0070 (0x0098 - 0x0028)
class ULeaderboardQueryCallbackProxy final : public UObject
{
public:
	TMulticastInlineDelegate<void(int32 LeaderboardValue)> OnSuccess;                                // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(int32 LeaderboardValue)> OnFailure;                                // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x50];                                      // 0x0048(0x0050)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class ULeaderboardQueryCallbackProxy* CreateProxyObjectForIntQuery(class APlayerController* PlayerController, class FName StatName);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LeaderboardQueryCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LeaderboardQueryCallbackProxy")
	}
	static class ULeaderboardQueryCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULeaderboardQueryCallbackProxy>();
	}
};
DUMPER7_ASSERTS_ULeaderboardQueryCallbackProxy;

// Class OnlineSubsystemUtils.LogoutCallbackProxy
// 0x0038 (0x0068 - 0x0030)
class ULogoutCallbackProxy final : public UBlueprintAsyncActionBase
{
public:
	TMulticastInlineDelegate<void(class APlayerController* PlayerController)> OnSuccess;             // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class APlayerController* PlayerController)> OnFailure;             // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x18];                                      // 0x0050(0x0018)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class ULogoutCallbackProxy* Logout(class UObject* WorldContextObject, class APlayerController* PlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LogoutCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LogoutCallbackProxy")
	}
	static class ULogoutCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULogoutCallbackProxy>();
	}
};
DUMPER7_ASSERTS_ULogoutCallbackProxy;

// Class OnlineSubsystemUtils.OnlineBeacon
// 0x0030 (0x0258 - 0x0228)
class AOnlineBeacon : public AActor
{
public:
	uint8                                         Pad_228[0x8];                                      // 0x0228(0x0008)(Fixing Size After Last Property [ Rei-SdkDumper ])
	float                                         BeaconConnectionInitialTimeout;                    // 0x0230(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         BeaconConnectionTimeout;                           // 0x0234(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UNetDriver*                             NetDriver;                                         // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_240[0x18];                                     // 0x0240(0x0018)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineBeacon")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineBeacon")
	}
	static class AOnlineBeacon* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOnlineBeacon>();
	}
};
DUMPER7_ASSERTS_AOnlineBeacon;

// Class OnlineSubsystemUtils.OnlineBeaconClient
// 0x0060 (0x02B8 - 0x0258)
class AOnlineBeaconClient : public AOnlineBeacon
{
public:
	class AOnlineBeaconHostObject*                BeaconOwner;                                       // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UNetConnection*                         BeaconConnection;                                  // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EBeaconConnectionState                        ConnectionState;                                   // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_269[0x4F];                                     // 0x0269(0x004F)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	void ClientOnConnected();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineBeaconClient")
	}
	static class AOnlineBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOnlineBeaconClient>();
	}
};
DUMPER7_ASSERTS_AOnlineBeaconClient;

// Class OnlineSubsystemUtils.OnlineBeaconHost
// 0x00B8 (0x0310 - 0x0258)
class AOnlineBeaconHost final : public AOnlineBeacon
{
public:
	int32                                         ListenPort;                                        // 0x0258(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Rei-SdkDumper ])
	TArray<class AOnlineBeaconClient*>            ClientActors;                                      // 0x0260(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_270[0xA0];                                     // 0x0270(0x00A0)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineBeaconHost")
	}
	static class AOnlineBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOnlineBeaconHost>();
	}
};
DUMPER7_ASSERTS_AOnlineBeaconHost;

// Class OnlineSubsystemUtils.OnlineBeaconHostObject
// 0x0028 (0x0250 - 0x0228)
class AOnlineBeaconHostObject : public AActor
{
public:
	class FString                                 BeaconTypeName;                                    // 0x0228(0x0010)(ZeroConstructor, Transient, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class AOnlineBeaconClient>        ClientBeaconActorClass;                            // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class AOnlineBeaconClient*>            ClientActors;                                      // 0x0240(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineBeaconHostObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineBeaconHostObject")
	}
	static class AOnlineBeaconHostObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOnlineBeaconHostObject>();
	}
};
DUMPER7_ASSERTS_AOnlineBeaconHostObject;

// Class OnlineSubsystemUtils.OnlineEngineInterfaceImpl
// 0x0100 (0x0128 - 0x0028)
class UOnlineEngineInterfaceImpl2 final : public UOnlineEngineInterface
{
public:
	class FName                                   VoiceSubsystemNameOverride;                        // 0x0028(0x0008)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_30[0xF8];                                      // 0x0030(0x00F8)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineEngineInterfaceImpl")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineEngineInterfaceImpl")
	}
	static class UOnlineEngineInterfaceImpl2* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineEngineInterfaceImpl2>();
	}
};
DUMPER7_ASSERTS_UOnlineEngineInterfaceImpl2;

// Class OnlineSubsystemUtils.OnlinePIESettings
// 0x0018 (0x0050 - 0x0038)
class UOnlinePIESettings final : public UDeveloperSettings
{
public:
	bool                                          bOnlinePIEEnabled;                                 // 0x0038(0x0001)(Edit, ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Rei-SdkDumper ])
	TArray<struct FPIELoginSettingsInternal>      Logins;                                            // 0x0040(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlinePIESettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlinePIESettings")
	}
	static class UOnlinePIESettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlinePIESettings>();
	}
};
DUMPER7_ASSERTS_UOnlinePIESettings;

// Class OnlineSubsystemUtils.OnlineSessionClient
// 0x01B8 (0x01E0 - 0x0028)
class UOnlineSessionClient final : public UOnlineSession
{
public:
	uint8                                         Pad_28[0x1B0];                                     // 0x0028(0x01B0)(Fixing Size After Last Property [ Rei-SdkDumper ])
	bool                                          bIsFromInvite;                                     // 0x01D8(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHandlingDisconnect;                               // 0x01D9(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1DA[0x6];                                      // 0x01DA(0x0006)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OnlineSessionClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OnlineSessionClient")
	}
	static class UOnlineSessionClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnlineSessionClient>();
	}
};
DUMPER7_ASSERTS_UOnlineSessionClient;

// Class OnlineSubsystemUtils.PartyBeaconClient
// 0x00C0 (0x0378 - 0x02B8)
class APartyBeaconClient final : public AOnlineBeaconClient
{
public:
	uint8                                         Pad_2B8[0x30];                                     // 0x02B8(0x0030)(Fixing Size After Last Property [ Rei-SdkDumper ])
	class FString                                 DestSessionId;                                     // 0x02E8(0x0010)(ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FPartyReservation                      PendingReservation;                                // 0x02F8(0x0050)(Protected, NativeAccessSpecifierProtected)
	EClientRequestType                            RequestType;                                       // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bPendingReservationSent;                           // 0x0349(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bCancelReservation;                                // 0x034A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_34B[0x2D];                                     // 0x034B(0x002D)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	void ClientCancelReservationResponse(EPartyReservationResult ReservationResponse);
	void ClientReservationResponse(EPartyReservationResult ReservationResponse);
	void ClientSendReservationFull();
	void ClientSendReservationUpdates(int32 NumRemainingReservations);
	void ServerCancelReservationRequest(const struct FUniqueNetIdRepl& PartyLeader);
	void ServerRemoveMemberFromReservationRequest(const class FString& SessionId, const struct FPartyReservation& ReservationUpdate);
	void ServerReservationRequest(const class FString& SessionId, const struct FPartyReservation& Reservation);
	void ServerUpdateReservationRequest(const class FString& SessionId, const struct FPartyReservation& ReservationUpdate);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PartyBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PartyBeaconClient")
	}
	static class APartyBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<APartyBeaconClient>();
	}
};
DUMPER7_ASSERTS_APartyBeaconClient;

// Class OnlineSubsystemUtils.PartyBeaconHost
// 0x0078 (0x02C8 - 0x0250)
class APartyBeaconHost final : public AOnlineBeaconHostObject
{
public:
	class UPartyBeaconState*                      State;                                             // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_258[0x60];                                     // 0x0258(0x0060)(Fixing Size After Last Property [ Rei-SdkDumper ])
	bool                                          bLogoutOnSessionTimeout;                           // 0x02B8(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2B9[0x3];                                      // 0x02B9(0x0003)(Fixing Size After Last Property [ Rei-SdkDumper ])
	float                                         SessionTimeoutSecs;                                // 0x02BC(0x0004)(ZeroConstructor, Transient, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TravelSessionTimeoutSecs;                          // 0x02C0(0x0004)(ZeroConstructor, Transient, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2C4[0x4];                                      // 0x02C4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PartyBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PartyBeaconHost")
	}
	static class APartyBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<APartyBeaconHost>();
	}
};
DUMPER7_ASSERTS_APartyBeaconHost;

// Class OnlineSubsystemUtils.PartyBeaconState
// 0x0050 (0x0078 - 0x0028)
class UPartyBeaconState final : public UObject
{
public:
	class FName                                   SessionName;                                       // 0x0028(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumConsumedReservations;                           // 0x0030(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MaxReservations;                                   // 0x0034(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumTeams;                                          // 0x0038(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumPlayersPerTeam;                                 // 0x003C(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FName                                   TeamAssignmentMethod;                              // 0x0040(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ReservedHostTeamNum;                               // 0x0048(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ForceTeamNum;                                      // 0x004C(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bRestrictCrossConsole;                             // 0x0050(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bEnableRemovalRequests;                            // 0x0051(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Rei-SdkDumper ])
	TArray<struct FPartyReservation>              Reservations;                                      // 0x0058(0x0010)(ZeroConstructor, Transient, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_68[0x10];                                      // 0x0068(0x0010)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PartyBeaconState")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PartyBeaconState")
	}
	static class UPartyBeaconState* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPartyBeaconState>();
	}
};
DUMPER7_ASSERTS_UPartyBeaconState;

// Class OnlineSubsystemUtils.QuitMatchCallbackProxy
// 0x0048 (0x0078 - 0x0030)
class UQuitMatchCallbackProxy final : public UOnlineBlueprintCallProxyBase
{
public:
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnFailure;                                         // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x28];                                      // 0x0050(0x0028)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UQuitMatchCallbackProxy* QuitMatch(class UObject* WorldContextObject, class APlayerController* PlayerController, const class FString& MatchID, EMPMatchOutcome Outcome, int32 TurnTimeoutInSeconds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("QuitMatchCallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuitMatchCallbackProxy")
	}
	static class UQuitMatchCallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuitMatchCallbackProxy>();
	}
};
DUMPER7_ASSERTS_UQuitMatchCallbackProxy;

// Class OnlineSubsystemUtils.ShowLoginUICallbackProxy
// 0x0030 (0x0060 - 0x0030)
class UShowLoginUICallbackProxy final : public UBlueprintAsyncActionBase
{
public:
	TMulticastInlineDelegate<void(class APlayerController* PlayerController)> OnSuccess;             // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class APlayerController* PlayerController)> OnFailure;             // 0x0040(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UShowLoginUICallbackProxy* ShowExternalLoginUI(class UObject* WorldContextObject, class APlayerController* InPlayerController);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ShowLoginUICallbackProxy")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShowLoginUICallbackProxy")
	}
	static class UShowLoginUICallbackProxy* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShowLoginUICallbackProxy>();
	}
};
DUMPER7_ASSERTS_UShowLoginUICallbackProxy;

// Class OnlineSubsystemUtils.SpectatorBeaconClient
// 0x00E8 (0x03A0 - 0x02B8)
class ASpectatorBeaconClient final : public AOnlineBeaconClient
{
public:
	uint8                                         Pad_2B8[0x30];                                     // 0x02B8(0x0030)(Fixing Size After Last Property [ Rei-SdkDumper ])
	class FString                                 DestSessionId;                                     // 0x02E8(0x0010)(ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FSpectatorReservation                  PendingReservation;                                // 0x02F8(0x0078)(Protected, NativeAccessSpecifierProtected)
	ESpectatorClientRequestType                   RequestType;                                       // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bPendingReservationSent;                           // 0x0371(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bCancelReservation;                                // 0x0372(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_373[0x2D];                                     // 0x0373(0x002D)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	void ClientCancelReservationResponse(ESpectatorReservationResult ReservationResponse);
	void ClientReservationResponse(ESpectatorReservationResult ReservationResponse);
	void ClientSendReservationFull();
	void ClientSendReservationUpdates(int32 NumRemainingReservations);
	void ServerCancelReservationRequest(const struct FUniqueNetIdRepl& Spectator);
	void ServerReservationRequest(const class FString& SessionId, const struct FSpectatorReservation& Reservation);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SpectatorBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpectatorBeaconClient")
	}
	static class ASpectatorBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASpectatorBeaconClient>();
	}
};
DUMPER7_ASSERTS_ASpectatorBeaconClient;

// Class OnlineSubsystemUtils.SpectatorBeaconHost
// 0x0078 (0x02C8 - 0x0250)
class ASpectatorBeaconHost final : public AOnlineBeaconHostObject
{
public:
	class USpectatorBeaconState*                  State;                                             // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_258[0x60];                                     // 0x0258(0x0060)(Fixing Size After Last Property [ Rei-SdkDumper ])
	bool                                          bLogoutOnSessionTimeout;                           // 0x02B8(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2B9[0x3];                                      // 0x02B9(0x0003)(Fixing Size After Last Property [ Rei-SdkDumper ])
	float                                         SessionTimeoutSecs;                                // 0x02BC(0x0004)(ZeroConstructor, Transient, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         TravelSessionTimeoutSecs;                          // 0x02C0(0x0004)(ZeroConstructor, Transient, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2C4[0x4];                                      // 0x02C4(0x0004)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SpectatorBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpectatorBeaconHost")
	}
	static class ASpectatorBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASpectatorBeaconHost>();
	}
};
DUMPER7_ASSERTS_ASpectatorBeaconHost;

// Class OnlineSubsystemUtils.SpectatorBeaconState
// 0x0038 (0x0060 - 0x0028)
class USpectatorBeaconState final : public UObject
{
public:
	class FName                                   SessionName;                                       // 0x0028(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         NumConsumedReservations;                           // 0x0030(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MaxReservations;                                   // 0x0034(0x0004)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bRestrictCrossConsole;                             // 0x0038(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Rei-SdkDumper ])
	TArray<struct FSpectatorReservation>          Reservations;                                      // 0x0040(0x0010)(ZeroConstructor, Transient, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_50[0x10];                                      // 0x0050(0x0010)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SpectatorBeaconState")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SpectatorBeaconState")
	}
	static class USpectatorBeaconState* GetDefaultObj()
	{
		return GetDefaultObjImpl<USpectatorBeaconState>();
	}
};
DUMPER7_ASSERTS_USpectatorBeaconState;

// Class OnlineSubsystemUtils.TestBeaconClient
// 0x0000 (0x02B8 - 0x02B8)
class ATestBeaconClient final : public AOnlineBeaconClient
{
public:
	void ClientPing();
	void ServerPong();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TestBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TestBeaconClient")
	}
	static class ATestBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATestBeaconClient>();
	}
};
DUMPER7_ASSERTS_ATestBeaconClient;

// Class OnlineSubsystemUtils.TestBeaconHost
// 0x0000 (0x0250 - 0x0250)
class ATestBeaconHost final : public AOnlineBeaconHostObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TestBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TestBeaconHost")
	}
	static class ATestBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATestBeaconHost>();
	}
};
DUMPER7_ASSERTS_ATestBeaconHost;

// Class OnlineSubsystemUtils.TurnBasedBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UTurnBasedBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void GetIsMyTurn(class UObject* WorldContextObject, class APlayerController* PlayerController, const class FString& MatchID, bool* bIsMyTurn);
	static void GetMyPlayerIndex(class UObject* WorldContextObject, class APlayerController* PlayerController, const class FString& MatchID, int32* PlayerIndex);
	static void GetPlayerDisplayName(class UObject* WorldContextObject, class APlayerController* PlayerController, const class FString& MatchID, int32 PlayerIndex, class FString* PlayerDisplayName);
	static void RegisterTurnBasedMatchInterfaceObject(class UObject* WorldContextObject, class APlayerController* PlayerController, class UObject* Object);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TurnBasedBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TurnBasedBlueprintLibrary")
	}
	static class UTurnBasedBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTurnBasedBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UTurnBasedBlueprintLibrary;

// Class OnlineSubsystemUtils.VoipListenerSynthComponent
// 0x0060 (0x0720 - 0x06C0)
class UVoipListenerSynthComponent final : public USynthComponent
{
public:
	uint8                                         Pad_6C0[0x60];                                     // 0x06C0(0x0060)(Fixing Struct Size After Last Property [ Rei-SdkDumper ])

public:
	bool IsIdling();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VoipListenerSynthComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VoipListenerSynthComponent")
	}
	static class UVoipListenerSynthComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVoipListenerSynthComponent>();
	}
};
DUMPER7_ASSERTS_UVoipListenerSynthComponent;

}

