#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_20

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_20.RandomBuff_20_C
// 0x0000 (0x0160 - 0x0160)
class URandomBuff_20_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RandomBuff_20_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomBuff_20_C")
	}
	static class URandomBuff_20_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_20_C>();
	}
};
DUMPER7_ASSERTS_URandomBuff_20_C;

}

