#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_2

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_2.RandomBuff_2_C
// 0x0000 (0x0160 - 0x0160)
class URandomBuff_2_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RandomBuff_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomBuff_2_C")
	}
	static class URandomBuff_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_2_C>();
	}
};
DUMPER7_ASSERTS_URandomBuff_2_C;

}

