#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_29

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_29.RandomBuff_29_C
// 0x0000 (0x0160 - 0x0160)
class URandomBuff_29_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RandomBuff_29_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomBuff_29_C")
	}
	static class URandomBuff_29_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_29_C>();
	}
};
DUMPER7_ASSERTS_URandomBuff_29_C;

}

