#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomBuff_103

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RandomBuff_103.RandomBuff_103_C
// 0x0000 (0x0160 - 0x0160)
class URandomBuff_103_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RandomBuff_103_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RandomBuff_103_C")
	}
	static class URandomBuff_103_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URandomBuff_103_C>();
	}
};
DUMPER7_ASSERTS_URandomBuff_103_C;

}

