#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RawInput

#include "Basic.hpp"

#include "RawInput_structs.hpp"


namespace SDK::Params
{

// Function RawInput.RawInputFunctionLibrary.GetRegisteredDevices
// 0x0010 (0x0010 - 0x0000)
struct RawInputFunctionLibrary_GetRegisteredDevices final
{
public:
	TArray<struct FRegisteredDeviceInfo>          ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RawInputFunctionLibrary_GetRegisteredDevices;

}

