#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScreenMatching

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class ScreenMatching.ScreenMatchingSettings
// 0x0010 (0x0038 - 0x0028)
class UScreenMatchingSettings final : public UObject
{
public:
	class FString                                 DeviceConfigureFilePath;                           // 0x0028(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static float GetSafeZoneRowValue();
	static bool IsMatched();
	static void UpdateZoomSafetyZone();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ScreenMatchingSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ScreenMatchingSettings")
	}
	static class UScreenMatchingSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScreenMatchingSettings>();
	}
};
DUMPER7_ASSERTS_UScreenMatchingSettings;

}

