#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMC_BaseMonster

#include "Basic.hpp"

#include "SMSystem_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SMC_BaseMonster.SMC_BaseMonster_C
// 0x0008 (0x01B0 - 0x01A8)
class USMC_BaseMonster_C final : public USMStateMachineComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void OnDie(class AGameCharacter* Character, class AGameCharacter* Killer, const struct FHealthChangeValue& HealthChangeValue);
	void ReceiveTick(float DeltaSeconds);
	void OnAIHasNewTarget(class AActor* Target);
	void ExecuteUbergraph_SMC_BaseMonster(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SMC_BaseMonster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SMC_BaseMonster_C")
	}
	static class USMC_BaseMonster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USMC_BaseMonster_C>();
	}
};
DUMPER7_ASSERTS_USMC_BaseMonster_C;

}

