#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TDRandomBuff_50

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TDRandomBuff_50.TDRandomBuff_50_C
// 0x0000 (0x0160 - 0x0160)
class UTDRandomBuff_50_C final : public UAbilityBufferSkill
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TDRandomBuff_50_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TDRandomBuff_50_C")
	}
	static class UTDRandomBuff_50_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTDRandomBuff_50_C>();
	}
};
DUMPER7_ASSERTS_UTDRandomBuff_50_C;

}

