#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UObjectPlugin

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "UObjectPlugin_structs.hpp"


namespace SDK
{

// Class UObjectPlugin.MyPluginObject
// 0x0010 (0x0038 - 0x0028)
class UMyPluginObject final : public UObject
{
public:
	struct FMyPluginStruct                        MyStruct;                                          // 0x0028(0x0010)(NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MyPluginObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MyPluginObject")
	}
	static class UMyPluginObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMyPluginObject>();
	}
};
DUMPER7_ASSERTS_UMyPluginObject;

}

