#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_watermark_Item

#include "Basic.hpp"

#include "uw_watermark_Item_classes.hpp"
#include "uw_watermark_Item_parameters.hpp"


namespace SDK
{

// Function uw_watermark_Item.uw_watermark_Item_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void Uuw_watermark_Item_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_watermark_Item.uw_watermark_Item_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uuw_watermark_Item_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "BP_OnItemExpansionChanged");

	Params::uw_watermark_Item_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_watermark_Item.uw_watermark_Item_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uuw_watermark_Item_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "BP_OnItemSelectionChanged");

	Params::uw_watermark_Item_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_watermark_Item.uw_watermark_Item_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uuw_watermark_Item_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "OnListItemObjectSet");

	Params::uw_watermark_Item_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function uw_watermark_Item.uw_watermark_Item_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Uuw_watermark_Item_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function uw_watermark_Item.uw_watermark_Item_C.ExecuteUbergraph_uw_watermark_Item
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uuw_watermark_Item_C::ExecuteUbergraph_uw_watermark_Item(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_watermark_Item_C", "ExecuteUbergraph_uw_watermark_Item");

	Params::uw_watermark_Item_C_ExecuteUbergraph_uw_watermark_Item Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

