#pragma once

/*
* SDK generated by Rei-SdkDumper
* Based on Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: uw_widgets_red_reward

#include "Basic.hpp"

#include "uw_widgets_red_reward_classes.hpp"
#include "uw_widgets_red_reward_parameters.hpp"


namespace SDK
{

// LuaFunction uw_widgets_red_reward.uw_widgets_red_reward_C.Destruct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_widgets_red_reward_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_widgets_red_reward_C", "Destruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_widgets_red_reward.uw_widgets_red_reward_C.Construct
// (BlueprintCosmetic, Native, Event, Public, BlueprintEvent)

void Uuw_widgets_red_reward_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_widgets_red_reward_C", "Construct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// LuaFunction uw_widgets_red_reward.uw_widgets_red_reward_C.OnConstruct
// (Native, Event, Public, BlueprintEvent)

void Uuw_widgets_red_reward_C::OnConstruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_widgets_red_reward_C", "OnConstruct");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function uw_widgets_red_reward.uw_widgets_red_reward_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString Uuw_widgets_red_reward_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("uw_widgets_red_reward_C", "GetModuleName");

	Params::uw_widgets_red_reward_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

